package projek;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author nanchaara
 */

public class Zakat extends javax.swing.JFrame {
    
    private void Kosongkan_Form() {
    kode_keluarga.setEditable(true);
    kode_keluarga.setText(null);
    kepala.setText(null);
    rt.clearSelection();
    jumlah_anggota.setText(null);
    anggota.setText(null);
    zakat_maal.setText(null);
    zakat_fitrah.setText(null);
    }
    
    private void Tampilkan_Data() {
        DefaultTableModel model = new DefaultTableModel ();
        model.addColumn ("No");
        model.addColumn ("Kode Keluarga");
        model.addColumn ("Kepala");
        model.addColumn ("RT");
        model.addColumn ("Jumlah Anggota");
        model.addColumn ("Anggota");
        model.addColumn ("Zakat Fitrah");
        model.addColumn ("Zakat Maal");
        
        try {
            
            int no = 1;
            
            String sql = "SELECT * FROM keluarga WHERE kode_keluarga LIKE '%"
                      + cari.getText () + "%'"
                      + "OR kepala LIKE '%" + cari.getText () + "%'";
            java.sql.Connection conn = (Connection) koneksiZakat.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(1),
                     res.getString(2), res.getString(3),
                     res.getString(4), res.getString(5),
                     res.getString(6), res.getString(7)});
            }
            tabel.setModel (model);
            
         } catch (SQLException e) {
            System.out.println ("Error : " + e.getMessage());
         }
    }
    /**
     * Creates new form Zakat
     */
    
    public Zakat() {
        initComponents();
        
        Tampilkan_Data();
        Kosongkan_Form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rt = new javax.swing.ButtonGroup();
        judul = new javax.swing.JLabel();
        label_kepala = new javax.swing.JLabel();
        kepala = new javax.swing.JTextField();
        label_jumlah = new javax.swing.JLabel();
        label_rt = new javax.swing.JLabel();
        rt5 = new javax.swing.JRadioButton();
        rt6 = new javax.swing.JRadioButton();
        rt7 = new javax.swing.JRadioButton();
        label_maal = new javax.swing.JLabel();
        zakat_maal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        judul1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        label_id = new javax.swing.JLabel();
        kode_keluarga = new javax.swing.JTextField();
        jumlah_anggota = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        label_fitrah = new javax.swing.JLabel();
        zakat_fitrah = new javax.swing.JTextField();
        label_anggota = new javax.swing.JLabel();
        anggota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        judul.setText("Zakat Masjid Al-Kautsar");

        label_kepala.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_kepala.setText("Nama Kepala");

        label_jumlah.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_jumlah.setText("Jumlah Anggota");

        label_rt.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_rt.setText("RT");

        rt.add(rt5);
        rt5.setText("5");
        rt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rt5ActionPerformed(evt);
            }
        });

        rt.add(rt6);
        rt6.setText("6");
        rt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rt6ActionPerformed(evt);
            }
        });

        rt.add(rt7);
        rt7.setText("7");
        rt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rt7ActionPerformed(evt);
            }
        });

        label_maal.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_maal.setText("Zakat Maal");

        btnTambah.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        judul1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        judul1.setText("Data Zakat Masjid Al-Kautsar");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Keluarga", "Nama Kepala", "RT", "Jumlah Anggota", "Anggota", "Zakat Fitrah", "Zakat Maal"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        label_id.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_id.setText("Kode Keluarga");

        btnSave.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        label_fitrah.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_fitrah.setText("Zakat Fitrah");

        label_anggota.setFont(new java.awt.Font("Inter Medium", 0, 11)); // NOI18N
        label_anggota.setText("Anggota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_anggota)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_fitrah)
                                .addComponent(label_maal)
                                .addComponent(label_jumlah)
                                .addComponent(label_rt)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(115, 115, 115)
                                            .addComponent(kode_keluarga, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(label_id))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_kepala)
                                        .addGap(45, 45, 45)
                                        .addComponent(kepala, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnClear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(zakat_maal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(zakat_fitrah, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlah_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rt5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rt6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rt7))))))
                        .addGap(16, 227, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(judul)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(judul1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(judul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kode_keluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_kepala)
                    .addComponent(kepala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rt5)
                    .addComponent(rt6)
                    .addComponent(rt7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fitrah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zakat_fitrah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_maal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zakat_maal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnClear)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rt5ActionPerformed

    private void rt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rt6ActionPerformed

    private void rt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rt7ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String rt = null;
        if (rt5.isSelected ()) {
            rt = "5";
        } else if (rt6.isSelected ()) {
            rt = "6";
        } else if (rt7.isSelected ()) {
            rt = "7";
        }
        
        try {
            String sql = "INSERT INTO keluarga VALUES ('" + kode_keluarga.getText()
                    + "','" + kepala.getText()
                    + "','" + rt
                    + "','" + jumlah_anggota.getText()
                    + "','" + anggota.getText()
                    + "','" + zakat_fitrah.getText()
                    + "','" + zakat_maal.getText() + "')";
            java.sql.Connection conn = (Connection) koneksiZakat.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil!");
            Tampilkan_Data();
            Kosongkan_Form();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog (this, e.getMessage ());
        }
        Kosongkan_Form();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String rt = null;
        if (rt5.isSelected ()) {
            rt = "5";
        } else if (rt6.isSelected ()) {
            rt = "6";
        } else if (rt7.isSelected ()) {
            rt = "7";
        }
        
        try {
            String sql = "UPDATE keluarga SET kode_keluarga ='" + kode_keluarga.getText()
                    + "', kepala='" + kepala.getText()
                    + "', rt='" + rt
                    + "', jumlah_anggota='" + jumlah_anggota.getText()
                    + "', anggota='" + anggota.getText()
                    + "', zakat_fitrah='" + zakat_fitrah.getText()
                    + "', zakat_maal='" + zakat_maal.getText()
                    + "' WHERE kode_keluarga = '" + kode_keluarga.getText() + "'";
            java.sql.Connection conn = (Connection) koneksiZakat.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog (this, e.getMessage());
        }
        Tampilkan_Data();
        Kosongkan_Form();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        Kosongkan_Form();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM keluarga WHERE kode_keluarga ='"
                    + kode_keluarga.getText () + "'";
            java.sql.Connection conn = (Connection) koneksiZakat.configDB () ;
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog (null, "Hapus Data Berhasil!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog (this, e.getMessage () );
        }
        Tampilkan_Data();
        Kosongkan_Form ();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM keluarga WHERE kode_keluarga LIKE '%"
                      + cari.getText () + "%'"
                      + "OR kepala LIKE '%" + cari.getText()
                      + "OR rt LIKE '%" + cari.getText();
            
            
            java.sql.Connection conn = (Connection) koneksiZakat.configDB () ;
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
        
        } catch (HeadlessException | SQLException e) {

        }
        Tampilkan_Data();
        Kosongkan_Form ();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.rowAtPoint(evt.getPoint());
        String kode = tabel.getValueAt(baris, 1).toString();
        kode_keluarga.setText(kode);
        
        String nama = tabel.getValueAt(baris, 2).toString();
        kepala.setText(nama);
        
        if ("5".equals(tabel.getValueAt (baris, 3).toString())) {
           rt5.setSelected (true);
        } else if ("6".equals(tabel.getValueAt (baris, 3).toString())) {
           rt6.setSelected (true);
        } else {
           rt7.setSelected (true);
        }
        String jml = tabel.getValueAt(baris, 4).toString();
        jumlah_anggota.setText(jml);
        
        String ang = tabel.getValueAt(baris, 5).toString();
        anggota.setText(ang);
        
        String zktF = tabel.getValueAt(baris, 6).toString();
        zakat_fitrah.setText(zktF);
        
        String zktM = tabel.getValueAt (baris, 7).toString() ;
        zakat_maal.setText(zktM);
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anggota;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField cari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JTextField jumlah_anggota;
    private javax.swing.JTextField kepala;
    private javax.swing.JTextField kode_keluarga;
    private javax.swing.JLabel label_anggota;
    private javax.swing.JLabel label_fitrah;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_jumlah;
    private javax.swing.JLabel label_kepala;
    private javax.swing.JLabel label_maal;
    private javax.swing.JLabel label_rt;
    private javax.swing.ButtonGroup rt;
    private javax.swing.JRadioButton rt5;
    private javax.swing.JRadioButton rt6;
    private javax.swing.JRadioButton rt7;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField zakat_fitrah;
    private javax.swing.JTextField zakat_maal;
    // End of variables declaration//GEN-END:variables

}